[project]
name = "dati-moody"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.1.3",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pyarrow>=18.0.0",
]
